
export const SESSION_CREATE_ATTEMPT = 'SESSION_CREATE_ATTEMPT';
export const SESSION_CREATE_FULFILLED = 'SESSION_CREATE_FULFILLED';
export const SESSION_CREATE_FAILED = 'SESSION_CREATE_FAILED';
export const SESSION_DESTROY_FULFILLED = 'SESSION_DESTROY_FULFILLED';
export const SESSION_CHECK_ATTEMPT = 'SESSION_CHECK_ATTEMPT';
export const SESSION_CHECK_FULFILLED = 'SESSION_CHECK_FULFILLED';
export const SESSION_CHECK_FAILED = 'SESSION_CHECK_FAILED';
export const SESSION_UPDATE_FULFILLED = 'SESSION_UPDATE_FULFILLED';
export const SESSION_UPDATE_FAILED = 'SESSION_UPDATE_FAILED';
export const SESSION_PASSWORD_CHANGE_ATTEMPT = 'SESSION_PASSWORD_CHANGE_ATTEMPT';
export const SESSION_PASSWORD_CHANGE_FAILED = 'SESSION_PASSWORD_CHANGE_FAILED';
export const SESSION_PASSWORD_CHAGE_FULFILLED = 'SESSION_PASSWORD_CHANGE_FULFILLED';
